version: 2.1
orbs:
  github-cli: circleci/github-cli@2.0

workflows:
  build:
    jobs:
      - linux-arm64v8:
          filters:
            tags:
              only: /^v.*/

jobs:
  linux-arm64v8:
    resource_class: arm.medium
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - github-cli/setup
      - run:
          name: Post Stats to GitHub PR
          command: |
          sudo apt-get install jq

          pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
          -u $GH_USER:$GH_TOKEN)

          if [ $(echo $pr_response | jq length) -eq 0 ]; then
            echo "No PR found to update"
          else
            pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
          fi

          curl --location --request POST "$pr_comment_url" \
          -u $GH_USER:$GH_TOKEN \
          --header 'Content-Type: application/json' \
          --data-raw '{
           "body": "This would be the data to add"
          }'
      - run: ./build.sh $(cat LIBVIPS_VERSION) linux-arm64v8
      - run: ./integrity.sh
      - when:
          condition: <<pipeline.git.tag>>
          steps:
            - run: gh release upload --repo "$(git config --get remote.origin.url)" $CIRCLE_TAG *.tar.gz *.integrity
